// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkaufkemqdjwmghbhufc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrYXVma2VtcWRqd21naGJodWZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NjEyNTMsImV4cCI6MjA2MDQzNzI1M30.zTek9WpX03bxoA6cG2gnbPgrHFZqIJI6HVCGQ9sdYi0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);